power_raw <- read.csv("household_power_consumption.txt",sep=";",na.strings="?")
power <- subset(power_raw,Date=="1/2/2007"|Date=="2/2/2007")
rm(power_raw)
power$Date <- strptime(paste(power$Date,power$Time),"%d/%m/%Y %H:%M:%S")
png("plot4.png")
par(mfrow=c(2,2))
plot(power$Date,power$Global_active_power,type="l",xlab="",ylab="Global Active Power")
plot(power$Date,power$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(power$Date,power$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
points(power$Date,power$Sub_metering_2,type="l",col="red")
points(power$Date,power$Sub_metering_3,type="l",col="blue")
legend("topright",lwd=c(1,1,1),col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty="n")
plot(power$Date,power$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()
