power_raw <- read.csv("household_power_consumption.txt",sep=";",na.strings="?")
power <- subset(power_raw,Date=="1/2/2007"|Date=="2/2/2007")
rm(power_raw)
png("plot1.png")
hist(power$Global_active_power,col="red",main="Global Active Power",xlab="Global Active Power (kilowatts)")
dev.off()
